---
- name: Ensure git build repo
  block:
  - name: Ensure build git repo
    ansible.builtin.git:
      repo: "{{ build_repo.url }}"
      dest: "{{ moodle_base_build_dir }}"
      clone: yes
      update: yes
      force: yes
      version: "{{ build_repo.version }}"
      refspec: '+refs/tags/*:refs/tags/*'
    changed_when: False

  rescue:
  - name: Delete git repo
    file:
      state: absent
      dest: "{{ moodle_base_build_dir }}"

  - name: Ensure build git repo
    ansible.builtin.git:
      repo: "{{ build_repo.url }}"
      dest: "{{ moodle_base_build_dir }}"
      clone: yes
      update: yes
      force: yes
      version: "{{ build_repo.version }}"
      refspec: '+refs/tags/*:refs/tags/*'
    changed_when: False

- name: Ensure moodle download from github
  lineinfile:
    path: "{{ moodle_base_dockerfile }}"
    state: "{{ item.state }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: yes
  changed_when: False
  loop:
    - { regexp: '(.*)curl -s -N(.*)', line: '        curl -L {{ moodle_tarball_url }} | tar -xvz && mv moodle* moodle && \', state: "present" }

- name: docker build base
  docker_image:
    name: "moodlebasebuild:{{ moodle_tag }}"
    build:
      path: "{{ moodle_base_build_dir }}"
      dockerfile: "{{ moodle_base_dockerfile }}"
      nocache: yes
      pull: yes
    source: build
  become: yes
  notify:
    - docker build custom moodle